// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qezwjfqrruypyheiubuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlendqZnFycnV5cHloZWl1YnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODI4MzEsImV4cCI6MjA2MTE1ODgzMX0.jK12YnyuLGFyC1_isQQrfqdaLzpr5NMWpFYZwBTypCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);